language: python
python:
    - "2.7"

sudo: off
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - >
        platformio ci src
        -l lib/_init
        -l lib/cable
        -l lib/cover
        -l lib/light
        -l lib/power
        -l lib/serve
        -l lib/shell
        -l lib/store
        -b d1 
        -b d1_mini
        -b esp07
        -b esp12e
        -b esp_wroom_02
        -b nodemcu
        -b nodemcuv2
        -b wifinfo
